# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districtName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='schoolsdata',
            name='assembly_name',
        ),
        migrations.RemoveField(
            model_name='schoolsdata',
            name='parliament_name',
        ),
        migrations.RemoveField(
            model_name='schoolsdata',
            name='village_name',
        ),
        migrations.AlterField(
            model_name='schoolsdata',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.district'),
        ),
    ]
