# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20170826_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='broom',
            new_name='broom_available',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='dustbin',
            new_name='dustbin_available',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='electric_fans',
            new_name='electric_bulbs_required',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='toilet_common',
            new_name='electric_fans_available',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='total_electric_bulbs_required',
            new_name='electric_fans_required',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='electricity',
            new_name='electricity_available',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='learning_and_playing_materials',
            new_name='learning_and_playing_materials_available',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='mats',
            new_name='mats_available',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='mops',
            new_name='mops_available',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='need_flooring',
            new_name='need_flooring_in_building',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='others_required',
            new_name='others_requirements',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='toilet_doors',
            new_name='toilet_doors_condition',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='total_electric_fans_required',
            new_name='water_storage_containers_in_toilets_required',
        ),
        migrations.RemoveField(
            model_name='school',
            name='wallsrepair_requirement_description',
        ),
        migrations.RemoveField(
            model_name='school',
            name='water_storage_containers_in_kitchen_toilets',
        ),
        migrations.AddField(
            model_name='school',
            name='plant_pots_available',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='walls_repair_requirement_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='bal_vikas_samiti_feedback',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='ceiling_requirement_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='cleanliness_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='door_repair_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='flooring_requirement_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='mothers_committee_feedback',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='window_repair_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
