# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 12:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20170826_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
