# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 11:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_auto_20170826_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('to_year', models.IntegerField(blank=True, null=True)),
                ('from_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=1000)),
                ('area', models.CharField(blank=True, max_length=1000)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('landmark', models.CharField(blank=True, max_length=1000)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('instidentification', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='school',
            name='block_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='district',
        ),
        migrations.RemoveField(
            model_name='school',
            name='location',
        ),
        migrations.RemoveField(
            model_name='school',
            name='pincode',
        ),
        migrations.DeleteModel(
            name='district',
        ),
        migrations.AddField(
            model_name='address',
            name='boundary_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Boundary'),
        ),
        migrations.AddField(
            model_name='school',
            name='address_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Address'),
        ),
    ]
